### ISSUE TITLE
Integrating Real-Time News Updates into Vlearnup's "Latest Updates and Insights" Section

### ISSUE THREAD

**Issue by VishalAadiith** [VishnuAmit/VLearnUp-ELearningHub#13]
### **Task Overview**
This task focuses on enhancing the "Latest Updates and Insights" section of the Vlearnup e-learning platform. You will replace the current dummy news with real-time news updates.

### **Your Role**
1. Clone the repository and run the project.
2. Install the necessary packages using `npm install`.
3. Start the application using `npm start`.
4. Once started, navigate to the "Latest Updates and Insights" section.

### **What Needs to be Done**
1. **Choose a News API**:
   - Select a reliable news API (e.g., [News API](https://newsapi.org/), [GNews](https://gnews.io/docs/), [Currents API](https://currentsapi.services/en/docs/)).

2. **API Key Registration**:
   - Sign up for an API key and review the documentation.

![Screenshot 2024-10-03 093733](https://github.com/user-attachments/assets/eeabf43d-0c89-4084-9ad8-5e9f1065eb15)
There are 4 spaces to insert the news. 

3. **To Change**:
    - In place of those dummy images, the thumbnail of current news should get displayed.
    - In place of text inside green banners, display the NEWS article publisher and for that 1st image, the banner is placed outside of the picture(Fix that)
    - And, Edit the dummy texts with current headings and that continuing lines below that...
    - When we click on the heading, it should get us to the article page

4. **Real-Time Updates**:
   - Use `setInterval` to fetch updates every 5 minutes.

If you have any questions, feel free to reach out!

**Comment by In-Saiyan** [comment]
please assign me

**Comment by Samarth981** [comment]
can I solve this issue?

**Comment by VishnuAmit** [comment]
hey @In-Saiyan and @Samarth981 . You can start working on it.

**Comment by VishnuAmit** [comment]
Hi @In-Saiyan . Looks good but it requires  few corrections.
![Screenshot 2024-10-03 173901](https://github.com/user-attachments/assets/22305b90-fffb-4c2f-99b6-2bd9697a611e)


This is before image.

The below one is after image.

![Screenshot 2024-10-03 173844](https://github.com/user-attachments/assets/cb3d9a12-367e-4256-a8ad-d1852accb40c)


Changes:
- Fix the styling. Kindly stick to the before image and follow the same styles.
- Fix the overlapping of the main image ie (read more) and put the banner (cnn) inside the image.
- 2 lines is enough followed by read more...
- Only educational news shld displayed.
- Make sure the particular section is responsive.

If you have any doubts, feel free to ask.

**Comment by In-Saiyan** [comment]
@VishalAadiith ok Ill keep those changes in my mind

currently the state is like this and I'm trying to figure out what is causing the gap in the middle
![image](https://github.com/user-attachments/assets/f4c6219f-09a6-4932-a7d0-adccbf152e00)

The classNames are a bit confusing

**Comment by In-Saiyan** [comment]
![image](https://github.com/user-attachments/assets/3e855e49-33bf-4640-bcd8-f97d66f12bf1)
How about this(still working)

**Comment by Samarth981** [comment]
Sorry, I think I am not able to solve this problem. I checked all you code
file after then I will try again.

**Comment by Samarth981** [comment]
Please do not check my above. Sorry related mail because I am not sending
this sorry related mail for you. Sent in error

**Comment by VishnuAmit** [comment]
hey @In-Saiyan , Looks good. But in the main picture, you can remove the read more since it is overlapping and I assume the hyperlink is set to the heading and not to the read more because I don't see read more in other 3 images.

And in the 2nd column, 2nd and 3rd image, the content for that started quite below the top horizontal imaginary line of the image. 

And yea, if you finish those, you can create a PR. Thanks.

**Comment by In-Saiyan** [comment]
> hey @In-Saiyan , Looks good. But in the main picture, you can remove the read more since it is overlapping and I assume the hyperlink is set to the heading and not to the read more because I don't see read more in other 3 images.
> 
> And in the 2nd column, 2nd and 3rd image, the content for that started quite below the top horizontal imaginary line of the image.
> 
> And yea, if you finish those, you can create a PR. Thanks.

The child divs are inside wrong parent divs, so they can't be fixed until I do a full redesign

let me know what to do because this is desgined very poorly, I can do a quickfix like restricting the title to two lines aswell...
![image](https://github.com/user-attachments/assets/7f9ce2a8-45a9-4a03-988d-fd1bdf0f6efe)

**Comment by VishnuAmit** [comment]
yea that sounds ok.

**Comment by In-Saiyan** [comment]
@VishnuAmit thanks for the response, much appreciated.
I've hotfixed the alignment of both divs and I'm putting up a PR.
![image](https://github.com/user-attachments/assets/1f208f0d-972a-41df-b3b1-751b695e0cde)
