### ISSUE TITLE
Fix the responsiveness of the HomePage

### ISSUE THREAD

**Issue by VishnuAmit** [VishnuAmit/VLearnUp-ELearningHub#16]
- To save time and focus on other parts like backend, I created this webpage with the help of figma and used locofy-ai to generate the react code. 

- As you can see the responsiveness is not that great for the homepage when we shrink it, Solving this would be much appreciable. 

- You can comment if your are interested.

**Comment by Thunder-Blaze** [comment]
Sir, please assign this issue to me
and thanks 😊
