### ISSUE TITLE
Fix the alignment of text in email

### ISSUE THREAD

**Issue by VishnuAmit** [VishnuAmit/VLearnUp-ELearningHub#19]
![image](https://github.com/user-attachments/assets/cee0d8e8-e8b8-4559-85d4-c105c1c8dd0b)

- When i type the email, the text goes to the left. It should move to the right.
- Make the footer responsive.

**Comment by Abhi0049k** [comment]
@VishnuAmit Would like to work on this issue

**Comment by BarryByte** [comment]
@VishnuAmit I want to work on this issue, Please assign this to me. Thanks.

**Comment by VishnuAmit** [comment]
hey @Abhi0049k and @BarryByte . Go ahead.
