### ISSUE TITLE
Website breaks due to unsafe property access on potentially undefined fields

### ISSUE THREAD

**Issue by ojasmaheshwari** [VishnuAmit/VLearnUp-ELearningHub#28]
![Screenshot_2024-10-04_22-16-22](https://github.com/user-attachments/assets/91528f7c-2495-491b-8023-1467d42e7bc3)

### Steps to reproduce
1) Run using `npm start`

The `truncateDescription` and `truncateTitle` functions are being used unsafely in `LatestUpdates.js`. Accessing a property on `description` which maybe undefined causes the website to break during development. I know that this problem likely won't persist in production mode. But for the aid of development, I believe it is better to add safety checks in these kinds of functions rather than a potential workaround of disabling react errors. If this is intended behavior, please let me know.
Fixed by adding optional chaining in `description`, `title` in `truncateDescription` and `truncateTitle` function.
Will raise a PR soon.

**Comment by VishnuAmit** [comment]
yea go ahead.

**Comment by ojasmaheshwari** [comment]
Raised #29
