### ISSUE TITLE
Implementing proper error messages and form validation on signup/login

### ISSUE THREAD

**Issue by ojasmaheshwari** [VishnuAmit/VLearnUp-ELearningHub#30]
### Problems
In the signup or login form, a generic error "Failed to sign up. Please try again." is shown whenever the request to Firebase is not successful. This might confuse the users as they won't be able to identify what have they done wrong while filling the form.
There is also a lack of form validation in the sign-up and login forms, allowing users to enter empty fields.

### Possible Fix
I would like to add specific error messages depending upon the `errorCode` received from Firebase which will inform users about their mistake in a simple and concise manner. I would also like to add semantic HTML attributes and features to make user experience more intuitive and smooth as well as enable form validation. I would also add DOM purification in the client side for safety against XSS and server attacks.

If this sounds reasonable, could you please assign this issue to me so that I can start working on it?

**Comment by VishnuAmit** [comment]
Well, keep going.

**Comment by Sunilverma99** [comment]
sir we can also integreate the signup using the google .

**Comment by VishnuAmit** [comment]
yea. Create a issue on that if you want to work on it. @Sunilverma99
