### ISSUE TITLE
The website is not responsive. In the screenshot you can see the hero section of the website is not responsive.

### ISSUE THREAD

**Issue by Sunilverma99** [VishnuAmit/VLearnUp-ELearningHub#32]
[
![Screenshot 2024-10-06 163232](https://github.com/user-attachments/assets/c5f97ade-33a5-44eb-8e9c-47e5077b3a3b)
](url)

**Comment by VishnuAmit** [comment]
yea..go for it @Sunilverma99

**Comment by ISaumya1011** [comment]
Hi @VishnuAmit , I am Hacktoberfest 2024 contributor. If this issue is still open, Can you please assign it to me.

**Comment by VishnuAmit** [comment]
Sorry, the issue has been solved already.
