### ISSUE TITLE
Feature Improvement: Improve 'Explore Courses' section.

### ISSUE THREAD

**Issue by RanjanaShenoy** [VishnuAmit/VLearnUp-ELearningHub#37]
I want to add different courses. Only AWS Cloud Practitioner course is present. I would improve this by adding various courses.
![image](https://github.com/user-attachments/assets/eb5fd8a1-4dfc-4070-9da0-f5efd47c688b)

**Comment by RanjanaShenoy** [comment]
Hi @VishnuAmit ,
I am a Hacktoberfest 2024 contributor.
Please assign this issue to me.

**Comment by VishnuAmit** [comment]
Alright. I have named 4 courses and you can see them in the streamfinder page. 
Display all those and replace dummy text with relevant statements. Make the cards functional and route to some dummy page.

**Comment by RanjanaShenoy** [comment]
Hi @VishnuAmit ,
I have raised a PR containing enhancements made to 4 courses.
Please don't close this issue. I will add more commits containing enhancements to the Explore Courses, dummy pages for courses.

**Comment by VishnuAmit** [comment]
Alright, @RanjanaShenoy. I'll merge your PR in a couple of hours.

**Comment by RanjanaShenoy** [comment]
Hi @VishnuAmit ,
I have added a new page AllCourses.js . This page contains details of all the courses. Route to this page is in FrameComponent.js. These changes are present in recent commit. 

![image](https://github.com/user-attachments/assets/0d5f0556-4c79-4148-b41a-11d0bf1d5a17)
![image](https://github.com/user-attachments/assets/9e7e570f-86d0-4c08-a2d7-efbd162e9be1)
![image](https://github.com/user-attachments/assets/c1f3586e-25b7-4c27-adf5-1c9152f7b9ed)
