### ISSUE TITLE
'See All Courses' Page doesn't have a link to navigate back to Homepage.

### ISSUE THREAD

**Issue by RanjanaShenoy** [VishnuAmit/VLearnUp-ELearningHub#41]
'See All Courses' Page doesn't have a link to navigate back to Homepage.
![image](https://github.com/user-attachments/assets/f2f1e599-fb5f-4181-b3af-2cd3f6847180)

Adding a link to navigate back (to HomePage) enhances the user experience, making it easier for user to move back after seeing all courses.

**Comment by RanjanaShenoy** [comment]
Hi @VishnuAmit ,
I am a Hacktoberfest 2024 contributor. I want to contribute by resolving this issue. Please assign this issue to me.

**Comment by VishnuAmit** [comment]
ok sure
