### ISSUE TITLE
Enhancements to VLearnUp website. 'What how it works' button and 'Enter access code' sections.

### ISSUE THREAD

**Issue by RanjanaShenoy** [VishnuAmit/VLearnUp-ELearningHub#43]
![image](https://github.com/user-attachments/assets/f7dc440b-e79c-4d03-9206-a6d53830a131)
![image](https://github.com/user-attachments/assets/0d3eed9f-e5f6-42dd-acf5-2693b0f8ea21)

Button 'Watch how it works' is not clickable. I would like to redirect to a YouTube video upon clicking. 
Also button 'Enter Access Code' is not clickable. I would like to add a page to enter access code for students.

**Comment by RanjanaShenoy** [comment]
Hi @VishnuAmit , I am Hacktoberfest 2024 contributor. Please assign this issue to me.

**Comment by ISaumya1011** [comment]
Hi @VishnuAmit , I want to contribute in Hacktoberfest as Hactoberfest 2024 contributor. Can you please assign this issue to me.
Thanks

**Comment by VishnuAmit** [comment]
Yea @RanjanaShenoy go for it.
