### ISSUE TITLE
Feature Improvement: Improvements in Text alignment in 'Explore Courses' section's courses.

### ISSUE THREAD

**Issue by RanjanaShenoy** [VishnuAmit/VLearnUp-ELearningHub#6]
![image](https://github.com/user-attachments/assets/59bc808f-94ff-45f6-b579-e23e745f231f)

![image](https://github.com/user-attachments/assets/ca56d088-9cf3-463c-b793-f4c58f5ebff6)

The padding left is not uniform for all items in the 'explore courses' section. There is an opportunity for improvement.
I would like to contribute to this issue by working on this improvement.

**Comment by RanjanaShenoy** [comment]
hi @VishnuAmit 
I am hacktoberfest 2024 contributor. I would like to contribute. Please assign this issue to me.

**Comment by vaishnav-3** [comment]
@VishnuAmit can i work on this ? will you assign it to me

**Comment by VishnuAmit** [comment]
@vaishnav-3 yea..
