### ISSUE TITLE
Integrating AI-Powered Chatbot with Gemini API into the E-Learning Platform Website

### ISSUE THREAD

**Issue by VishalAadiith** [VishnuAmit/VLearnUp-ELearningHub#8]
### **Task Overview**
This task focuses on developing an e-learning platform with advanced features. You are tasked with integrating the **chatbot assistance** (Pro Feature 3) that is already connected to the Gemini API into the platform's website.

### **Your Role**
1. Clone the repository and run the project.
2. Install the necessary packages using `npm install`.
3. Start the application using `npm start`.
4. Once started, sign up and go to the dashboard, where you can find the button for *Pro Feature 3* (Chatbot Assistance).
5. Run the chatbot script in the backend folder using the command:

   ```bash
   python chatbot.py
# **What Needs to be Done**

## **Frontend Chat Interface:**
- Create a **chatbox** on the website where users can send queries to the chatbot.
- The UI should be **clean**, **user-friendly**, and **responsive**, allowing for seamless interaction on both desktop and mobile devices.
- Include features like **message history**, **minimization**, and **expansion** of the chat window.

## **Backend Integration:**
- Use **API calls** (such as Axios or Fetch API) to send user queries from the frontend to the backend chatbot, which is powered by the **Gemini API**.
- Ensure that **responses from the chatbot** are displayed on the frontend in real-time.

## **Real-time Communication:**
- Ensure the communication between the frontend and backend is **asynchronous**, allowing for real-time responses without page reloads.
- Use **WebSockets** or **REST API** depending on the preferred implementation, to establish this connection.


## **Feel Free to Use:**
- Any **external libraries** for frontend enhancements (e.g., **Socket.io** for real-time communication or **Axios** for making API calls).
- Design frameworks like **Bootstrap** or **Material-UI** to improve the chat interface.

**Comment by slashexx** [comment]
What are you planning to do about the API key ?

If I work locally, I'll use mine ofc but what about deployment ?

**Comment by VishnuAmit** [comment]
Hey @slashexx . You can use your own Gemini API key and test it locally.  And about message history, no need to store it for a user, But there should be a button that closes the chat and till that message history should be displayed in the chatbot even if we navigate to another page and come back. 

If you are willing to do it, let me know ill assign you and you can start working on this.

- Chatbot should be displayed in the bottom right corner(only in dashboard page) and minimizing and expansion should be handled. 
- A good UI is mandatory. 

Good luck.

**Comment by slashexx** [comment]
Sure thing then, I'd love to work on it, please assign it to me.

**Comment by VishnuAmit** [comment]
Alright, Carry on.

**Comment by slashexx** [comment]
Thanks for assigning !

I have a question, as I was working to implement the backend of the chatbot via using the pages router (/api/chat), I noticed that there was another python ('chatbot.py') code in the backend directory....

Which method should I use to implement it then ? I'm comfortable using nextjs but in case you require me to handle it via python, I'm fine with that too.

**Comment by VishnuAmit** [comment]
Hey, Don't worry about chatbot.py folder. I did it in other project and was trying to just integrate it here due to some reasons. You are flexible to use anything that you want to meet the desired outputs.
